export const TEXTO_HEADER = "*** PROMOÇÃO DE INAUGURAÇÃO DA IMTIMAS ***";
export const LOCALIZACAO = "São Paulo";
export const PESQUISAR_PRODUTO = "Pesquisar produto...";
export const INFORME_O_CEP = "Informe seu CEP";
// export const CONSULTAR_FRETE = "Consultar frete e prazo de entrega"
export const CONSULTAR_FRETE = "Consultar frete";
export const CEP = "CEP";
export const SUA_LOCALIZACAO = "Sua localização";
export const TODAS_CATEGORIAS = "CATEGORIAS";
// export const VALOR_E_PRAZO = "O valor e prazo de entrega podem variar de acordo com sua localização."
export const VALOR_E_PRAZO = "Os prazos podem variar.";
